import { Track } from './types';

export const CURATED_TRACKS_FALLBACK: Track[] = [
  // Top Trending on Instagram Reels & YouTube
  {
    id: 'tr1',
    title: 'Tauba Tauba',
    artist: 'Karan Aujla (Bad Newz)',
    source: 'youtube',
    urlOrVideoId: 'LK7-_xhn3c8',
    durationSec: 218,
    thumbnail: 'https://img.youtube.com/vi/LK7-_xhn3c8/hqdefault.jpg',
    category: 'Trending Reels',
  },
  {
    id: 'tr2',
    title: 'Big Dawgs',
    artist: 'Hanumankind & Kalmi',
    source: 'youtube',
    urlOrVideoId: 'hOHKltAiKXQ',
    durationSec: 234,
    thumbnail: 'https://img.youtube.com/vi/hOHKltAiKXQ/hqdefault.jpg',
    category: 'Trending Reels',
  },
  {
    id: 'tr3',
    title: 'Espresso',
    artist: 'Sabrina Carpenter',
    source: 'youtube',
    urlOrVideoId: 'eVli-tstM5E',
    durationSec: 175,
    thumbnail: 'https://img.youtube.com/vi/eVli-tstM5E/hqdefault.jpg',
    category: 'Trending Reels',
  },
  {
    id: 'tr4',
    title: 'Birds of a Feather',
    artist: 'Billie Eilish',
    source: 'youtube',
    urlOrVideoId: 'd5gf9dXHevw',
    durationSec: 196,
    thumbnail: 'https://img.youtube.com/vi/d5gf9dXHevw/hqdefault.jpg',
    category: 'Trending Reels',
  },
  {
    id: 'tr5',
    title: 'Die With A Smile',
    artist: 'Lady Gaga & Bruno Mars',
    source: 'youtube',
    urlOrVideoId: 'kPa7bsKwL-8',
    durationSec: 251,
    thumbnail: 'https://img.youtube.com/vi/kPa7bsKwL-8/hqdefault.jpg',
    category: 'Romantic & Couple',
  },
  {
    id: 'tr6',
    title: 'Aayi Nai (Stree 2)',
    artist: 'Pawan Singh, Simran Choudhary, Sachin-Jigar',
    source: 'youtube',
    urlOrVideoId: 'y1ozWpLpDlc',
    durationSec: 178,
    thumbnail: 'https://img.youtube.com/vi/y1ozWpLpDlc/hqdefault.jpg',
    category: 'YouTube Top Grossing',
  },
  {
    id: 'tr7',
    title: 'Illuminati',
    artist: 'Sushin Shyam & Dabzee (Aavesham)',
    source: 'youtube',
    urlOrVideoId: 'tOM-nWPcR4U',
    durationSec: 195,
    thumbnail: 'https://img.youtube.com/vi/tOM-nWPcR4U/hqdefault.jpg',
    category: 'Trending Reels',
  },
  {
    id: 'tr8',
    title: 'Millionaire',
    artist: 'Yo Yo Honey Singh (Glory)',
    source: 'youtube',
    urlOrVideoId: 'XO8wew38VM8',
    durationSec: 198,
    thumbnail: 'https://img.youtube.com/vi/XO8wew38VM8/hqdefault.jpg',
    category: 'YouTube Top Grossing',
  },
  {
    id: 'tr9',
    title: 'Sajni (Laapataa Ladies)',
    artist: 'Arijit Singh & Ram Sampath',
    source: 'youtube',
    urlOrVideoId: 'k3g_WjLCsgo',
    durationSec: 170,
    thumbnail: 'https://img.youtube.com/vi/k3g_WjLCsgo/hqdefault.jpg',
    category: 'Romantic & Couple',
  },
  {
    id: 'tr10',
    title: 'Jo Tum Mere Ho',
    artist: 'Anuv Jain',
    source: 'youtube',
    urlOrVideoId: 'gHDdeV2p_p8',
    durationSec: 251,
    thumbnail: 'https://img.youtube.com/vi/gHDdeV2p_p8/hqdefault.jpg',
    category: 'Romantic & Couple',
  },
  {
    id: 'tr11',
    title: 'Husn',
    artist: 'Anuv Jain',
    source: 'youtube',
    urlOrVideoId: 'gJLVTKhTnog',
    durationSec: 218,
    thumbnail: 'https://img.youtube.com/vi/gJLVTKhTnog/hqdefault.jpg',
    category: 'Romantic & Couple',
  },
  {
    id: 'tr12',
    title: 'Gulabi Sadi',
    artist: 'Sanju Rathod',
    source: 'youtube',
    urlOrVideoId: 'q8Pe_Y37U18',
    durationSec: 202,
    thumbnail: 'https://img.youtube.com/vi/q8Pe_Y37U18/hqdefault.jpg',
    category: 'Trending Reels',
  },
  {
    id: 'tr13',
    title: 'Beautiful Things',
    artist: 'Benson Boone',
    source: 'youtube',
    urlOrVideoId: 'Oa_RSwwpPaA',
    durationSec: 180,
    thumbnail: 'https://img.youtube.com/vi/Oa_RSwwpPaA/hqdefault.jpg',
    category: 'Trending Reels',
  },
  {
    id: 'tr14',
    title: 'One Love',
    artist: 'Shubh',
    source: 'youtube',
    urlOrVideoId: '4Ty64s3k4gA',
    durationSec: 158,
    thumbnail: 'https://img.youtube.com/vi/4Ty64s3k4gA/hqdefault.jpg',
    category: 'YouTube Top Grossing',
  },
  {
    id: 'tr15',
    title: 'Kesariya (Brahmāstra)',
    artist: 'Arijit Singh & Pritam',
    source: 'youtube',
    urlOrVideoId: 'g6fnFALEseI',
    durationSec: 268,
    thumbnail: 'https://img.youtube.com/vi/g6fnFALEseI/hqdefault.jpg',
    category: 'Romantic & Couple',
  },
  {
    id: 'tr16',
    title: 'Perfect',
    artist: 'Ed Sheeran',
    source: 'youtube',
    urlOrVideoId: '2Vv-BfVoq4g',
    durationSec: 263,
    thumbnail: 'https://img.youtube.com/vi/2Vv-BfVoq4g/hqdefault.jpg',
    category: 'Romantic & Couple',
  },
  {
    id: 'tr17',
    title: 'Until I Found You',
    artist: 'Stephen Sanchez',
    source: 'youtube',
    urlOrVideoId: 'GxldQ9eX2wo',
    durationSec: 178,
    thumbnail: 'https://img.youtube.com/vi/GxldQ9eX2wo/hqdefault.jpg',
    category: 'Romantic & Couple',
  },
  // Guaranteed Audio Streaming (Royalty Free)
  {
    id: 'l1',
    title: 'Lo-Fi Chill Beats: Rainy Night',
    artist: 'SyncTune Studio',
    source: 'audio',
    urlOrVideoId: 'https://cdn.freesound.org/previews/612/612610_5674468-lq.mp3',
    durationSec: 154,
    thumbnail: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=80',
    category: 'Chill & Lo-Fi',
  },
  {
    id: 'l2',
    title: 'Synthwave Midnight Drive',
    artist: 'Neon Horizon',
    source: 'audio',
    urlOrVideoId: 'https://cdn.freesound.org/previews/530/530704_11861866-lq.mp3',
    durationSec: 180,
    thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&auto=format&fit=crop&q=80',
    category: 'Electronic',
  },
];
